version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales of Greenweez table in BigQuery - 1 row per products_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        freshness:
          warn_after: { count: 90, period: day }
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: single order id for a given customer
          - name: pdt_id
            description: id of the products sold by greenweez
          - name: revenue
            description: cash in - turnover generated buy the products sold
          - name: quantity
            description: number of units sold
      - name: product
        identifier: raw_gz_product
        description: table of greenweez products in BigQuery
        columns:
          - name: products_id
            description: id of the products sold by greenweez - PK of the table
            tests:
              - unique
          - name: purchase_price
            description: cash in - price of a given product
      - name: ship
        identifier: raw_gz_ship
        description: table of shipping info of Greenweez in BigQuery
        columns:
          - name: orders_id
            description: single order id for a given customer - PK of the table
            tests:
              - unique
          - name: shipping_fee
            description: cost - what greeweez pays to the carrier
          - name: logcost
            description: cash out
          - name: ship_cost
            description: cash in
      - name: adwords
        identifier: raw_gz_adwords
        description: table of the various costs related to the Google ads campaigns
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click
        columns:
          - name: date_date
            description: primary key - date of the campaign
          - name: campaign_key
            description: primary key
          - name: paid_source
            description: name of the source (here Google)
          - name: campaign_name
            description: specific name associated to as specific campaign under the format IA - COM - [PUR - ACQ] - DABA
          - name: ads_cost
            description: cost associated with the google ads
          - name: impression
            description: number of impressions the ads bring
          - name: click
            description: number of clicks the impressions bring
      - name: bing
        identifier: raw_gz_bing
        description: table of the various costs related to the Bing ads campaigns
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click
        columns:
          - name: date_date
            description: primary key - date of the campaign
          - name: campaign_key
            description: primary key
          - name: paid_source
            description: name of the source (here Bing)
          - name: campaign_name
            description: specific name associated to as specific campaign under the format IA - COM - [PUR - ACQ] - DABA
          - name: ads_cost
            description: cost associated with the Bing ads
          - name: impression
            description: number of impressions the ads bring
          - name: click
            description: number of clicks the impressions bring
      - name: criteo
        identifier: raw_gz_criteo
        description: table of the various costs related to the Criteo ads campaigns
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click
        columns:
          - name: date_date
            description: primary key - date of the campaign
          - name: campaign_key
            description: primary key
          - name: paid_source
            description: name of the source (here Criteo)
          - name: campaign_name
            description: specific name associated to as specific campaign under the format IA - COM - [PUR - ACQ] - DABA
          - name: ads_cost
            description: cost associated with the Criteo ads
          - name: impression
            description: number of impressions the ads bring
          - name: click
            description: number of clicks the impressions bring
      - name: facebook
        identifier: raw_gz_facebook
        description: table of the various costs related to the Google ads campaigns
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click
        columns:
          - name: date_date
            description: primary key - date of the campaign
          - name: campaign_key
            description: primary key
          - name: paid_source
            description: name of the source (here Facebook)
          - name: campaign_name
            description: specific name associated to as specific campaign under the format IA - COM - [PUR - ACQ] - DABA
          - name: ads_cost
            description: cost associated with the Facebook ads
          - name: impression
            description: number of impressions the ads bring
          - name: click
            description: number of clicks the impressions bring
models:
  - name: int_sales_margin
    description: sales margin calcultation per product
    columns:
      - name: products_id
        description: primary key
      - name: orders_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order
      - name: quantity
        description: sum of quantity per order
      - name: purchase_price
        description: price of one product (sales)
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
        #- not null:
        #column_name:
        #  - orders_id
        #  - products_id
        #  - margin
        #  - purchase_cost
        #  - date_date
        #  - revenue
        #  - quantity
        #  - purchase_price
  - name: int_orders_margin
    description: margin calcultation per order
    columns:
      - name: orders_id
        description: primary key
      - name: total_margin
        description: Margin = Revenue - Purchase_cost
      - name: date_date
        description: date of the order
      - name: total_revenue
        description: sum of revenue per order
      - name: total_quantity
        description: sum of quantity per order
    tests:
      - unique:
          column_name: orders_id
      - not_null:
          column_name:
            - date_date
            - orders_id
            - total_margin
            - total_quantity
            - total_revenue
  - name: int_orders_operational
    description: operational margin calcultation per order
    columns:
      - name: orders_id
        description: primary key
      - name: total_margin
        description: Margin = Revenue - Purchase_cost grouped by orders
      - name: date_date
        description: date of the order
      - name: total_revenue
        description: sum of revenue per order
      - name: total_quantity
        description: sum of quantity per order
      - name: shipping_fee
        description: cost - what greeweez pays to the carrier
      - name: logcost
        description: cash out
      - name: ship_cost
        description: cash in
      - name: operational_margin
        description: total_margin + shipping_fee - logcost - ship_cost
    tests:
      - unique:
          column_name: orders_id
      - not_null:
          column_name:
            - orders_id
            - date_date
            - total_margin
            - total_revenue
            - total_quantity
            - shipping_fee
            - logcost
            - ship_cost
            - operational_margin
  - name: finance_days
    description: summary of financial KPIs for analysis
    columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost grouped by orders
      - name: date_date
        description: date of the order
      - name: nb_transactions
        description: total number of orders aggregated
      - name: revenue
        description: sum of revenue per order
      - name: total_operational_margin
        description: total_margin + shipping_fee - logcost - ship_cost
      - name: average_basket
        description: total revenue / number of orders
    tests:
      - unique:
          column_name: "(nb_transactions || '-' || revenue)"
      - not_null:
          column_name:
            - date_date
            - nb_transactions
            - revenue
            - average_basket
            - margin
            - total_operational_margin
  - name: int_campaigns
    description: summary of the various media campaigns and their associated costs
    columns:
      - name: date_date
        description: primary key - date of the campaign
      - name: campaign_key
        description: primary key
      - name: paid_source
        description: name of the media sources
      - name: campaign_name
        description: specific name associated to as specific campaign
      - name: ads_cost
        description: cost associated with the ads
      - name: impression
        description: number of impressions the ads bring
      - name: click
        description: number of clicks the impressions bring
    tests:
      - unique:
          column_name: "(date_date || '-' || campaign_key)"
      - not_null:
          column_name:
            - date_date
            - paid_source
            - campaign_key
            - campaign_name
            - ads_cost
            - impression
            - click
  - name: int_campaigns_day
    description: summary of the aggregated ads costs
    columns:
      - name: date_date
        description: primary key - date of the campaign
      - name: ads_cost
        description: cost associated with the ads
      - name: impression
        description: number of impressions the ads bring
      - name: click
        description: number of clicks the impressions bring
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name:
            - date_date
            - ads_cost
            - impression
            - click
  - name: finance_campaigns_day
    description: summary of the ads_margin column requested by marketing and finance team and grouped by day 
    columns:
      - name: date_date
        description: primary key - date of the campaign
      - name: campaign_key
        description: primary key
      - name: paid_source
        description: name of the media sources
      - name: campaign_name
        description: specific name associated to as specific campaign
      - name: ads_cost
        description: cost associated with the ads
      - name: impression
        description: number of impressions the ads bring
      - name: click
        description: number of clicks the impressions bring
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name:
            - date_date
            - paid_source
            - campaign_key
            - campaign_name
            - ads_cost
            - impression
            - click
  - name: finance_campaigns_month
    description: summary of the ads_margin column requested by marketing and finance team grouped by month
    columns:
      - name: datemonth
        description: primary key - date grouped by month
      - name: ads_cost
        description: cost associated with the ads
      - name: impression
        description: number of impressions the ads bring
      - name: click
        description: number of clicks the impressions bring
    tests:
      - unique:
          column_name: datemonth
      - not_null:
          column_name:
            - datemonth
            - ads_cost
            - impression
            - click
